### ISSUE TITLE
npm run exec isn't handling colors or styles.

### ISSUE THREAD

**Issue by johngray1965** [zeplin/zem#18]
When I first developed the Flutter extension a little over a year ago, npm run exec listed out things for colors and textstyles.  Now I get:

Function “colors” not defined.
Function “textStyles” not defined.

I spent quite a while staring at my code trying to figure why it thought they weren't defined, sure looked okay.  Then I notice I get the same thing on the react native extension.   And colors and textStyles work when using the plugin is used as a local plugin.

**Comment by dirtybit** [comment]
This is fixed with v0.4.4
