### ISSUE TITLE
Flutter Plugin: Font Size half that of what is defined in the guide

### ISSUE THREAD

**Issue by tiholic** [zeplin/zem#8]
Flutter plugin

Font size 20sp is changed to 10.0 in the generated styles.

![image](https://user-images.githubusercontent.com/14252381/41397525-20cb8b52-6fd2-11e8-89be-f6f3e05a348e.png)

Please let me know if I am missing anything. Should I be using `textScaleFactor`?

---------

PS: I couldn't find the developer repo, please let know the details

**Comment by kardeslik** [comment]
Hi @tiholic,
This seems to be related to the project density.
You can contact with the developer of the Flutter Zeplin Extension.
Here is the developer repo link: https://github.com/johngray1965/FlutterZeplinExtension

**Comment by tiholic** [comment]
Thank you
